<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="DELL" name="com.w2a.architectbatch1.testCases.TestCase1" tests="3" failures="0" timestamp="28 Oct 2017 08:34:47 GMT" time="52.515" errors="1">
  <testcase name="afterMethod" time="13.683" classname="com.w2a.architectbatch1.testCases.TestCase1">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.w2a.architectbatch1.baseSetup.TestSetUp.afterMethod(TestSetUp.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:731)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- afterMethod -->
  <testcase name="tc_01" time="38.832" classname="com.w2a.architectbatch1.testCases.TestCase1"/>
  <testcase name="tc_02" time="0.000" classname="com.w2a.architectbatch1.testCases.TestCase1">
    <skipped/>
  </testcase> <!-- tc_02 -->
</testsuite> <!-- com.w2a.architectbatch1.testCases.TestCase1 -->
